# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "users", :force => true do |t|
    t.column "screen_name", :string
    t.column "email",       :string
    t.column "password",    :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

end
